### ISSUE TITLE
Issues with loading functions

### ISSUE THREAD

**Issue by Camry2731** [AmbitionsTechnologyGroup/ATG-PS-Functions#26]
So I wanted to start by saying that all of these functions are amazing, and I'm glad I happened to randomly stumble upon them. Its saved me hours of having to type functions that I was starting to write on my own.

The issue I'm having is loading the functions. I'm loading them in from the command on the readme `iwr tinyurl.com/get-atgps -useb | iex` and it will wait a few seconds, before giving a message about them not loading successfully. However, and this is the way I've gotten it work so far, if I put another instance of the same command in the script after the first instance of the command, it will then proceed to work fine. 

There also appears to be issues with the Update-DellPackages function, but I'll have to dig into the logs to figure out what the exact issue is with that and report back on another issue. Any other info I can provide I will be more then willing.

**Comment by tobraha** [comment]
Hey @Camry2731 - glad you like the scripts!

Hard to say exactly what's going on when you try loading the scripts, but you may be able to troubleshoot this a bit. If you follow the redirect of the tinyurl link, you'll find the loader script called 'Get-ATGPS.txt'.

This script tries to configure a few TLS settings before loading everything; you might be seeing some issues there. Also, it attempts to download all of the individual scripts (as modules) into `C:\Ambitions\Functions`. If you don't run the loader script as administrator, it may also fail when it tries to create that folder.

You could maybe try downloading that loader script and debugging it to see where it's failing for you.

If you can add some additional debugging info here, we may be able to assist further. Let us know!

-Tommy

**Comment by RCShoemaker** [comment]
Definitely let us know!
