### ISSUE TITLE
Add shortened URL's

### ISSUE THREAD

**Issue by tobraha** [AmbitionsTechnologyGroup/ATG-PS-Functions#7]
Sir @RCShoemaker,

I added a list of the shortened url's that I created:  https://github.com/AmbitionsTechnologyGroup/ATG-PS-Functions/blob/master/Scripts/misc/urls.txt

Can you add all of the tinyurl addresses associated with this project for reference?

**Comment by RCShoemaker** [comment]
Completed.

**Comment by tobraha** [comment]
Hmm for some reason I thought we had more shorteners with tinyurl...   guess I have a tinybrain.

Reference:  b49e1f95b8
